package com.example.campaignreach.reach.channel;

import java.time.Instant;

/**
 * Renders a single local-only smoke-test email from a {@link ReachMessage} (design.md §信件樣板; spec
 * requirement「Local email template shall be simple and deterministic」).
 *
 * <p>This is deliberately <strong>not</strong> a marketing template engine and does <strong>not</strong>
 * consult any registered template catalog: the local email delivery flow exists only to make a send
 * observable during local smoke tests, so the first version ships exactly <em>one</em> built-in generic
 * template. Consequently an unknown-but-non-blank {@code templateRef} is <em>not</em> an error — it is
 * echoed into the generic template rather than rejected, so a local smoke run never fails merely because
 * a template name is unrecognized.
 *
 * <p>The contract that a {@code templateRef} must be present is <em>not</em> this renderer's
 * responsibility: it is already enforced upstream by the {@link ReachMessage} compact constructor (and
 * the {@code ClaimedTask} invariant), which reject a null/blank {@code templateRef} before a message can
 * ever reach the renderer. This class intentionally does not re-validate that, so it cannot accidentally
 * paper over an invalid message contract by emitting a generic template for a blank reference.
 *
 * <p>The send time is passed <em>in</em> rather than read from the clock inside this class. That keeps
 * rendering deterministic and trivially unit-testable, and avoids a hidden {@code Instant.now()} call —
 * the (future) local SMTP provider supplies the timestamp, matching the sequence-diagram contract
 * {@code Renderer.render(message, now)}.
 *
 * <p>This is a plain, Spring-free class with no bean annotation on purpose: wiring it is the local
 * provider configuration's job (and must stay behind the local-profile gate), so annotating it as a
 * {@code @Component} here would risk registering it outside that gate.
 */
public final class LocalEmailTemplateRenderer {

    private static final String SUBJECT_PREFIX = "[Local Campaign Reach]";

    private static final String LOCAL_TEST_NOTICE =
            "This is a LOCAL TEST email from campaign-reach-system. It was generated by the local "
                    + "smoke-test template and is not a real marketing message.";

    /**
     * Renders the generic local test email for the given message and send time.
     *
     * @param message the unit of work to render; its {@code templateRef} is guaranteed non-blank by the
     *     {@link ReachMessage} invariant, so this method does not re-validate it
     * @param sentAt the send time supplied by the caller (kept out of this class for determinism)
     * @return the rendered subject and body
     * @throws NullPointerException if {@code message} or {@code sentAt} is null (a programming error: the
     *     caller is expected to hand in a valid, already-validated message and a real timestamp)
     */
    public RenderedEmail render(ReachMessage message, Instant sentAt) {
        if (message == null) {
            throw new NullPointerException("message must not be null");
        }
        if (sentAt == null) {
            throw new NullPointerException("sentAt must not be null");
        }

        String subject = SUBJECT_PREFIX + " " + message.templateRef();

        String body = LOCAL_TEST_NOTICE
                + System.lineSeparator()
                + System.lineSeparator()
                + "templateRef: "
                + message.templateRef()
                + System.lineSeparator()
                + "userId: "
                + message.userId()
                + System.lineSeparator()
                + "channel: "
                + message.channel()
                + System.lineSeparator()
                + "sentAt: "
                + sentAt;

        return new RenderedEmail(subject, body);
    }
}
